Objetivo 1
Paszser/IV pull request #5
Opened 2021-09-25 19:35 UTC by Paszser

2021-09-26 15:51 UTC, JJ commented
Tienes tú mismo un conflicto. Os rogaría que tratárais de que el PR estuviera listo para fusionarse antes de enviarlo. Por otro lado
1. Los milestones tienen que seguir un orden lógico. M1 parece ir antes que M2, sin embargo no hay ninguna HU asignada a M1
2. Los milestones tienen que describir un producto mínimamente viable. Un "sistema" no lo es. Hay que aclarar en qué va a consistir ese sistema.
3. El problema no está muy bien descrito, sólo que es un "comparador". La lógica de negocio parece clara, pero como el problema no está claro, no sabemos si los precios de videojuegos varían al día, a la semana, a la hora, qué horizonte vamos a predecir, si se va a predecir tiempo o cantidad, si se va a trabajar sobre títulos específicos o en general sobre conjuntos de videojuegos de un tipo determinado, en general, falta concreción.
4. No hay una descripción del titpo de usuario ni un user journey. Sin ella, es imposible saber por qué la clasificación #3 es importante para la lógica de negocio, 
Tampoco queda muy claro por qué esta aplicación tiene que ejecutarse en la nube, y por qué no es simplemente una aplicación de escritorio.

2021-09-28 10:06 UTC, Paszser commented
@JJ Realizada las modificaciones pertinentes. Espero que esté todo más claro y sea más conciso y cualquier cosa que deba ser mejor explicada o cambiada será bienvenida :D.

2021-09-28 11:11 UTC, JJ requested changes
Por favor, mira el concepto de producto mínimamente viable. M1 no es un milestone, *todas* las aplicaciones tienen que almacenar la información, pero el M1 tiene que pasar por lo necesario para implementar la lógica de negocio.
En el resto, tienes que describir el producto, lo que se va a producir.

2021-09-28 11:11 UTC, JJ commented on README.md
> +A su vez se incorpora una sección en el que las tendencias de videojuegos son resaltados así como novedades (véase lanzamientos, juegos en auge, tendencias...). Se podrán buscar dichos títulos por di
Esto déjalo en "nice to have", pero aparte de ser una tarea de interfaz de usuario, no está relacionada ni afecta a la lógica de negocio.

2021-09-28 11:11 UTC, JJ commented on docs/ISSUES.md
> +-Visualizador, usuario que simplemente hace uso de la aplicación para obtener información general de los título sin ánimo de compra.
A menos que vayas a extraer datos para poder hacer predicciones de este usuario. Por ejemplo, ¿influyen en los precios que la gente busque o no?

2021-09-28 11:11 UTC, JJ commented on docs/ISSUES.md
> +[HU1](https://github.com/Paszser/IV/issues/3) - Clasificación según el características del videojuego: Como visualizador me gustaría poder buscar las ofertas de videojuegos filtrándolos por el género
Tarea de UI, no tiene ningún beneficio, no queda muy claro qué papel juega.

2021-09-28 11:11 UTC, JJ commented on docs/ISSUES.md
> +
El "Dado que" en este caso es imprescindible, ya que la lógica de negocio depende totalmente de ello. ¿En base a qué vas a predecir una rebaja?
También ¿de qué videojuegos vas a calcular rebajas? ¿De todos? ¿De los que se usen en #3? ¿De otro tipo?

2021-09-28 11:11 UTC, JJ commented on docs/ISSUES.md
> +[HU3](https://github.com/Paszser/IV/issues/6) - Búsqueda de título: Como cliente me gustaría poder tener la opción de guardar ciertos títulos de alguna forma y hacer un seguimiento de actualizaciones
Tarea de interfaz de usuario, ninguna relación con la lógica de negocio.

2021-10-01 08:53 UTC, Paszser commented
@JJ Creo que está todo mejorado nuevamente y corregido, y preparado para una nueva corrección. Creo que M1 se modificó a un producto mínimamente viable que introduce la lógica de negocio así como corregidas las diversas facetas señaladas como funciones de UI.

2021-10-01 15:23 UTC, JJ approved these changes
No sé muy bien qué significa "despliegue" de precios, pero bueno, has descrito todo como producto mínimamente viable, y le tocará a @alexespana programar el objetivo siguiente.

2021-10-01 15:36 UTC, Paszser commented
Procedo a realizar el merge y anoto el nombre de mi compañero. ¡Gracias!

2021-10-01 15:37 UTC, merged